wandb_version: 1

B:
  desc: null
  value: 10
C:
  desc: null
  value: 0.6
E:
  desc: null
  value: 1
K:
  desc: null
  value: 12
R:
  desc: null
  value: 500
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1676882602.768155
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.13.10
      8:
      - 5
criterion:
  desc: null
  value: torch.nn.CrossEntropyLoss
device:
  desc: null
  value: cuda
eval_interval:
  desc: null
  value: 10
eval_task:
  desc: null
  value: ver
evaluate:
  desc: null
  value: false
fl_dataset_path:
  desc: null
  value: /workspace/flearn_data
gpu_ids:
  desc: null
  value:
  - 0
  - 1
  - 2
group_listfilenames:
  desc: null
  value:
  - /workspace/flearn_data/ver_list_G1_VER.txt
  - /workspace/flearn_data/ver_list_G2_VER.txt
  - /workspace/flearn_data/ver_list_G3_VER.txt
  - /workspace/flearn_data/ver_list_G4_VER.txt
  - /workspace/flearn_data/ver_list_G5_VER.txt
  - /workspace/flearn_data/ver_list_G6_VER.txt
  - /workspace/flearn_data/ver_list_G7_VER.txt
  - /workspace/flearn_data/ver_list_G8_VER.txt
  - /workspace/flearn_data/ver_list_G9_VER.txt
  - /workspace/flearn_data/ver_list_G10_VER.txt
  - /workspace/flearn_data/ver_list_G11_VER.txt
  - /workspace/flearn_data/ver_list_G12_VER.txt
group_size:
  desc: null
  value: 12
hidden_channels:
  desc: null
  value: 32
in_channels:
  desc: null
  value: 1
init_gain:
  desc: null
  value: 1.0
init_type:
  desc: null
  value: xavier
is_mp:
  desc: null
  value: false
listfilename:
  desc: null
  value: /workspace/flearn_data/ver_list_G12_VER.txt
log_name:
  desc: null
  value: FL.log
log_path:
  desc: null
  value: ../FL_log/2023-02-20_08:43:16
lr:
  desc: null
  value: 0.01
model_path:
  desc: null
  value: /nvme1/zhiyong/ASV_LOGS_202102/train_logs_201120/xvector(vox2)/model/model000000134.model
momentum:
  desc: null
  value: 0.9
multi_dataset_files:
  desc: null
  value:
  - /workspace/flearn_data/train_list_G1.txt
  - /workspace/flearn_data/train_list_G2.txt
  - /workspace/flearn_data/train_list_G3.txt
  - /workspace/flearn_data/train_list_G4.txt
  - /workspace/flearn_data/train_list_G5.txt
  - /workspace/flearn_data/train_list_G6.txt
  - /workspace/flearn_data/train_list_G7.txt
  - /workspace/flearn_data/train_list_G8.txt
  - /workspace/flearn_data/train_list_G9.txt
  - /workspace/flearn_data/train_list_G10.txt
  - /workspace/flearn_data/train_list_G11.txt
  - /workspace/flearn_data/train_list_G12.txt
multi_train_paths:
  desc: null
  value:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
name:
  desc: null
  value: CNN
num_classes:
  desc: null
  value: 10
num_hiddens:
  desc: null
  value: 512
optimizer:
  desc: null
  value: torch.optim.SGD
seed:
  desc: null
  value: 5959
speaker_init_model:
  desc: null
  value: /nvme1/zhiyong/ASV_LOGS_202102/train_logs_201120/xvector(vox2)/model/model000000134.model
tb_host:
  desc: null
  value: 0.0.0.0
tb_port:
  desc: null
  value: 5252
testfile_path:
  desc: null
  value: /workspace/flearn_data
use_additional_model:
  desc: null
  value:
  - true
  - false
